openapi: 3.0.1
info:
  title: Strive M5 APIS
  version: 1.0.0
  description: Endpoints for blog posts
servers:
  - url: 'http://localhost:3001'
    variables: {}
    description: Local Server
  - url: 'https://m5fs21mayd7.herokuapp.com'
    variables: {}
    description: Remote Server
paths:
  /blogPosts:
    summary: Endpoints related to blog posts
    description: CRUD for blog posts......
    get:
      summary: Fetch blog posts list
      description: ''
      operationId: ''
      responses:
        "200": #status code
          description: Everything fine
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/blogPost"

      tags:
        - blogPosts
      parameters:
        - in: query
          name: category
          schema:
            type: string

    post:
      summary: Create a new Blog post
      description: ''
      operationId: ''
      responses:
        default:
          description: Default error sample response
      tags:
        - blogs
tags:
  - name: blogs
    description: Blogs Endpoints
components:
  schemas:
    Blog post:
      type: object
      properties:
        author:
          type: string
        title:
          type: string
        category:
          type: string
        content:
          type: string
